# Generated by Django 3.0.4 on 2020-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerstudent',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/students/'),
        ),
    ]
